class EffectPriority:
    # on_turn_start
    TURN_START_INFO_PRIORITY = 2
    RECEIVE_MANA_PRIORITY = 1

    # receive_damage
    PUNISHMENT_PRIORITY = 3
    RECEIVE_DAMAGE_CHANGE_TARGET_PRIORITY = 2.5
    RECEIVE_DAMAGE_CANCELING_PRIORITY = 2
    RECEIVE_DAMAGE_DAMAGE_ATTACKER_PRIORITY = 1.7
    RECEIVE_DAMAGE_ABSORB_PRIORITY = 1.5
    MANA_SHIELD_PRIORITY = 1
    RECEIVE_DAMAGE_AFTER_DAMAGE_PRIORITY = 0.5

    # on_turn_end
    TURN_END_DAMAGE_PRIORITY = 1
    TURN_END_INFO_PRIORITY = 0.5

    # can_play
    CAN_PLAY_CANCELING_PRIORITY = 1

    # play
    PLAY_ALTERING_PRIORITY = 2
    PLAY_CANCELING_PRIORITY = 1

    # imprison
    IMPRISON_CANCEL_PRIORITY = 1
