class EffectPriority:
    # on_turn_start
    TURN_START_INFO_PRIORITY = 2
    RECEIVE_MANA_PRIORITY = 1

    # receive_damage
    PUNISHMENT_PRIORITY = 3
    RECEIVE_DAMAGE_CANCELING_PRIORITY = 2
    MANA_SHIELD_PRIORITY = 1

    # on_turn_end
    TURN_END_DAMAGE_PRIORITY = 1
    TURN_END_INFO_PRIORITY = 0.5

    # can_play
    CAN_PLAY_CANCELING_PRIORITY = 1

    # play
    PLAY_CANCELING_AND_ALTERING_PRIORITY = 1
